name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps
      - run: git pull
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12  
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "str-explorer"
          heroku_email: "oxana@vild.ly"
